### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by kaishijeng** [Gernby/raspberry-pilot#14]
Will this repository intend to use raspberry PI instead of  EON kit to run openpilot?

Thanks,

**Comment by EasternPA** [comment]
Yes. Please see this recent video showing the Raspberry Pi connected to the Panda over the mirror instead of an EON or Comma Two. @Gernby uses it daily and we are collaborating to make the installation process more universal for other users.

Note that this is only for Hondas with the Bosch Sensing System at this time.

https://www.youtube.com/watch?v=F-sCjVc2HvA

**Comment by kaishijeng** [comment]
@EasternPA 

Interesting, I don't have Hondas with Bosch Sensing system to try it. 
Just curious, how does Raspberry do lane detection which openpilot code needs snapdragon DSP accelerator to run  *.dlc model?

**Comment by EasternPA** [comment]
@kaishijeng I will let @Gernby provide technical details when he can, but the Bosch system already performs the lane detection. OpenPilot aims to create a universal approach to Lane Keeping with performance that far exceeds the typical performance of the stock systems. The Bosch system appears to produce perfectly usable output but in no way applies universally across all manufacturers.
