### ISSUE TITLE
ACC

### ISSUE THREAD

**Issue by TNPilot** [Gernby/raspberry-pilot#39]
Not so much of an issue, but will the ACC work down to 0mph, or does it cut off at 25mph like stock? Thanks.

**Comment by makifb** [comment]
How would the comma pedal work with raspberry pilot?

**Comment by Gernby** [comment]
Sorry for the delayed response.  

ACC is stock in Raspberry-Pilot, so it would cut off at the same speed.

The Comma pedal would be useless for the same reason.

**Comment by EasternPA** [comment]
> Not so much of an issue, but will the ACC work down to 0mph, or does it cut off at 25mph like stock? Thanks.

The ACC does not "cut off" below 25 MPH. If a car in front of you slows to a stop, RP (just like OP) will also slow to a complete stop and automatically resume once traffic starts moving again. You cannot set the desired maximum speed below 25, but the car does slow down to 0 in traffic, wait patiently, and automatically resume again when it is time to get going.

I agree the Pedal does not apply to a Bosch Honda. That was used on Nidec Hondas and older Toyotas that actually did shut off ACC below a certain speed like 28 MPH. Since the Bosch takes you down to 0 and back up again, you don't need a Pedal.
